#############################################################################
#   $ make all         compile and link all programs
#   $ make clean       clean objects and the executable file
##==========================================================================
CC := javac

all: Simpella

Simpella: 
	@- $(RM) *.class
	${CC} *.java
	@- echo "Compiled Successfully!!!"
        

##==========================================================================
#clean:
	
#	@- echo "Data Cleansing Done.Ready to Compile"


